fix local cmd

diff --git a/files/local/start b/files/local/start
--- a/files/local/start
+++ b/files/local/start
@@ -27,7 +27,7 @@ CURR_FOLDER="$(pwd)"
 cd $CURR_FOLDER
 
 unset BUILD_CMD
-BUILD_CMD=false
+BUILD_CMD='echo "empty cmd"'
 
 unset IGNORE_RUN
 IGNORE_RUN=false
@@ -66,30 +66,20 @@ fi
 # Build and RUN
 if $BUILD; then
 
-	if $BUILD_CMD; then
-		ok "Building cmd: ${BUILD_CMD} ---> ${OPT}"
-		eval ${BUILD_CMD}
-		if test $? -ne 0; then
-			abort "Build failed"
-		fi
-	fi
+	$BUILD_CMD
+	test $? -ne 0 && abort "Build failed" || ok "Building cmd: ${BUILD_CMD} ---> ${OPT}"
 
 	if $IGNORE_RUN; then
 		exit 0
 	fi
 
-	eval ${RUN_CMD}
+	$RUN_CMD
 	exit 0
 fi
 
 ok "Running cmd: ${WATCH_CMD}"
 
 # Watch
-eval ${WATCH_CMD}
-# $WATCH_CMD
-
-if test $? -ne 0; then
-	abort "Watch failed"
-fi
+eval $WATCH_CMD
 
 exit 0
