fix .env path

diff --git a/files/docker/start b/files/docker/start
--- a/files/docker/start
+++ b/files/docker/start
@@ -63,6 +63,9 @@ docker compose \
 	$DAEMON \
 	$SERVICE
 
-test $? -ne 0 && abort "Docker Compose up failed" || ok "Stopped gracefully"
+# test $? -ne 0 && abort "Start failed" || ok "Stopped gracefully"
+if test $? -ne 0; then
+	abort "Start failed"
+fi
 
 exit 0
